### 회원 가입 - 같은 이메일로 로그인하면 MemberException 반환
POST http://localhost:8081/signup/member
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234",
  "name": "홍길동",
  "phone": "010-1111-1111"
}

### 로그인 성공
POST http://localhost:8081/signIn/member
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1234"
}

### 로그인 실패 - 이메일 입력 오류
POST http://localhost:8081/signIn/member
Content-Type: application/json

{
  "email": "fail@test.com",
  "password": "1234"
}

### 로그인 실패 - 비밀번호 입력 오류
POST http://localhost:8081/signIn/member
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1111"
}